### ISSUE TITLE
AttributeError: 'WindowsPath' object has no attribute 'walk'

### ISSUE THREAD

**Issue by Mario-0** [SS-NES/codescholar#2]
Hello, I'm trying to run the code auditor in a Jupyther notebook in Visual Study Code but I get an error.
I have no idea why and I cannot find documentation on how to resolve it. 
Any suggestions? 

![Image](https://github.com/user-attachments/assets/0292c2ba-fe4b-493e-b4a2-dfdd3c143e5f)

**Comment by girgink** [comment]
Thanks for the issue report. The problem was due to a method (`Path.walk`), which was not supported in Python 3.11. I replaced it with a supported one (`os.walk`), which should solve the issue.

Can you please check if the main branch version works? You can install it by using the following command, if you have `pip` and `git` installed:

```
pip install git+https://github.com/SS-NES/code-auditor.git
```

I want to note that as indicated in the README, in the current version of the package, `analyse` method is renamed as `audit`. Hence, you should use the following command to create an audit report:

```
report = codeauditor.audit('.')
```

**Comment by Mario-0** [comment]
Unfortunately I keep getting an error. Despite checking via `pip list`  that code-auditor 0.2.1 is installed correctly after running `pip install git+https://github.com/SS-NES/code-auditor.git`

Any idea how to resolve this? 

I am no expert in programming so the issue could be well on my side.. thanks for thinking along! 

![Image](https://github.com/user-attachments/assets/47ad323b-a9b0-434d-a74a-29633d3c00f3)

**Comment by girgink** [comment]
Hi Mario, I don't think that you have the latest version installed. The latest version of codeauditor had the `audit()` method. The error indicates that the version you installed doesn't have it, so it is not the latest version. Did you uninstall the previous version before installing the latest version from the code repository? If not, probably `pip` didn't install it. Please make sure that you install it. In the `pip list` output, you should see the Github repository listed.

**Comment by Mario-0** [comment]
Thank you again! I tried the following. After `pip uninstall code-auditor` I see; 
```
Found existing installation: code-auditor 0.2.1
Uninstalling code-auditor-0.2.1:
  Would remove:
    c:\users\bootmr\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\scripts\codeauditor.exe
    c:\users\bootmr\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages\code_auditor-0.2.1.dist-info\*
    c:\users\bootmr\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages\codeauditor\*
Proceed (Y/n)? y
  **Successfully uninstalled code-auditor-0.2.1**
```
If I then check `pip list`, code auditor is not in the list. Both pip and git are installed. 
I then reinstall it via `pip install git+https://github.com/SS-NES/code-auditor.git`, and see `Successfully installed code-auditor-0.2.1`
If I run the code from the screenshot above again, I still get the same error :( 
Do you have any other ideas about how to solve it?
